apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: nginxservice
  labels:
    app: nginx
    layer: frontend
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
