apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-group25-web-europe-docker-pkg-dev-asgroup25-registry-as-25-dvwa-latest-write-in-shm-dir
  namespace: dvwa-group25-web
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      app: dvwa-web
      tier: frontend
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
