apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-group25-web-europe-docker-pkg-dev-asgroup25-registry-as-25-dvwa-latest-crypto-miners
  namespace: dvwa-group25-web
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /usr/local/bin/
      readOnly: true
      recursive: true
    - dir: /sbin/
      readOnly: true
      recursive: true
    - dir: /bin/
      readOnly: true
      recursive: true
    - dir: /usr/bin/
      readOnly: true
      recursive: true
    - dir: /var/local/bin/
      readOnly: true
      recursive: true
    - dir: /boot/
      readOnly: true
      recursive: true
  message: cryptominer detected and blocked
  process:
    matchDirectories:
    - dir: /tmp/
      recursive: true
    matchPaths:
    - execname: xmrig
    - execname: dero
    - execname: dero-miner-linux-amd64
    - execname: dero-wallet-cli-linux-amd64
    - execname: derod-linux-amd64
    - execname: zgrab2
    - execname: masscan
    - execname: nmap
    - execname: apt
    - execname: apk
    - execname: ntpdate
  selector:
    matchLabels:
      app: dvwa-web
      tier: frontend
  severity: 10
  tags:
  - cryptominer
  - MITRE_T1496_resource_hijacking
