---
apiVersion: apps/v1
kind: Deployment


###
### Deployment Metadata
###
metadata:
  name: dvwa-group25-web
  namespace: dvwa-group25-web


###
### Specs
###
spec:
  replicas: 1

  selector:
    matchLabels:
      app: dvwa-web
      tier: frontend

  template:

    # Template Metadata to be used by service for discovery
    metadata:
      labels:
        app: dvwa-web
        tier: frontend

    # Container/Volume definition
    spec:
      serviceAccountName: sa-web
      containers:
        - name: dvwa
          image: europe-docker.pkg.dev/asgroup25/registry-as-25/dvwa:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 300m
          env:
            - name: DB_SERVER
              value: dvwa-mysql-service.dvwa-group25-mysql.svc.cluster.local