apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dvwa
  namespace: dvwa-group25-web
spec:
  defaultBackend:
    service:
      name: dvwa-web-service
      port:
        number: 8080
