apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-web
  namespace: dvwa-group25-web
subjects:
- kind: ServiceAccount
  name: sa-web
  namespace: dvwa-group25-web
roleRef:
  kind: Role
  name: role-web
  apiGroup: rbac.authorization.k8s.io
