---
apiVersion: v1
kind: Secret
metadata:
  name: dvwa-secrets
  namespace: dvwa-group25-mysql
type: Opaque
data:
  ROOT_PASSWORD: czNyMDB0cGE1NQ==
  DVWA_USERNAME: ZHZ3YQ==
  DVWA_PASSWORD: cEBzc3cwcmQ=
  DVWA_DATABASE: ZHZ3YQ==
