apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sa-web
    namespace: dvwa-group25-web
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sa-mysql
    namespace: dvwa-group25-mysql
