apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa\
  namespace: dvwa-group25-web
  annotations:
    autoscaling.kubernetes.io/scale-down-stabilization: "30s"
    autoscaling.kubernetes.io/scale-up-stabilization: "30s"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dvwa-group25-web
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40