apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-group25-mysql-europe-docker-pkg-dev-asgroup25-registry-as-25-mariadb-10-latest-network-service-scanning
  namespace: dvwa-group25-mysql
spec:
  action: Audit
  message: Network service has been scanned!
  process:
    matchPaths:
    - path: /usr/bin/netstat
    - path: /bin/netstat
    - path: /usr/sbin/ip
    - path: /usr/bin/ip
    - path: /sbin/ip
    - path: /bin/ip
    - path: /usr/sbin/iw
    - path: /sbin/iw
    - path: /usr/sbin/ethtool
    - path: /sbin/ethtool
    - path: /usr/sbin/ifconfig
    - path: /sbin/ifconfig
    - path: /usr/sbin/arp
    - path: /sbin/arp
    - path: /usr/sbin/iwconfig
    - path: /sbin/iwconfig
  selector:
    matchLabels:
      app: dvwa-mysql
      tier: backend
  severity: 5
  tags:
  - MITRE
  - FGT1046
  - FIGHT
  - 5G
