apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-group25-mysql-europe-docker-pkg-dev-asgroup25-registry-as-25-mariadb-10-latest-impair-defense
  namespace: dvwa-group25-mysql
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/apparmor.d/
      recursive: true
    - dir: /etc/sysconfig/selinux/
      recursive: true
    matchPaths:
    - path: /etc/selinux/semanage.conf
  message: Selinux Files Accessed by Unknown Process
  selector:
    matchLabels:
      app: dvwa-mysql
      tier: backend
  severity: 6
  tags:
  - MITRE
  - FGT1562
  - FIGHT
  - 5G
